version: "3.7"

services:
  db:
    image: postgres:12
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=delta-source
      - POSTGRES_USER=delta
      - POSTGRES_PASSWORD=delta
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
