version: "3.7"
services:
  spark-master:
    image: spark-master:2.3.1
    build:
      context: ./master
      dockerfile: spark-master.Dockerfile
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
    networks:
      spark-network:

  spark-worker-1:
    image: spark-worker:2.3.1
    build:
      context: ./worker
      dockerfile: spark-worker.Dockerfile
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    env_file: worker/worker.env
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    volumes:
      - ./mnt/spark-data:/opt/spark-data
      - ./mnt/spark-jars:/opt/spark-jars
    networks:
      spark-network:

  spark-worker-2:
    image: spark-worker:2.3.1
    build:
      context: ./worker
      dockerfile: spark-worker.Dockerfile
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    env_file: worker/worker.env
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    volumes:
      - ./mnt/spark-data:/opt/spark-data
      - ./mnt/spark-jars:/opt/spark-jars
    networks:
      spark-network:

networks:
  spark-network:
